route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 3h
  receiver: 'web.hook'
  routes:
  - match:
      severity: 'critical'
    receiver: 'critical'
  - match:
      severity: 'warning'
    receiver: 'warning'

receivers:
- name: 'web.hook'
  webhook_configs:
  - url: 'http://localhost:5001/'
- name: 'critical'
  webhook_configs:
  - url: 'http://localhost:5001/critical'
- name: 'warning'
  webhook_configs:
  - url: 'http://localhost:5001/warning'

templates:
- '/etc/alertmanager/template/*.tmpl'

inhibit_rules:
- source_match:
    severity: 'critical'
  target_match:
    severity: 'warning'
  equal: ['alertname', 'dev', 'instance']
