apiVersion: 1

contactPoints:
  - orgId: 1
    name: Slack - Payment Service
    receivers:
      - uid: slack_payment_service
        type: webhook
        settings:
          url: $SLACK_WEBHOOK_URL
          httpMethod: POST
        disableResolveMessage: false

  - orgId: 1
    name: Email - Critical Alerts
    receivers:
      - uid: email_critical
        type: email
        settings:
          addresses: oncall@data2-ai.comppel
          singleEmail: false
        disableResolveMessage: false

  - orgId: 1
    name: Email - Platform Team
    receivers:
      - uid: email_platform
        type: email
        settings:
          addresses: platform-team@data2-ai.comppel
          singleEmail: false
        disableResolveMessage: false

  - orgId: 1
    name: Slack + Email - Critical
    receivers:
      - uid: slack_critical
        type: webhook
        settings:
          url: $SLACK_WEBHOOK_CRITICAL
          httpMethod: POST
        disableResolveMessage: false
      - uid: email_critical_combined
        type: email
        settings:
          addresses: oncall@data2-ai.comppel
          singleEmail: false
        disableResolveMessage: false
